### ISSUE TITLE
spvcm warning raised in pysal meta package

### ISSUE THREAD

**Issue by sjsrey** [pysal/spvcm#11]
![2020-01-24-1238-1579898292-sel](https://user-images.githubusercontent.com/118042/73102399-9c89ef00-3ea6-11ea-9a2f-ee61c84b3fbb.png)

**Comment by knaaptime** [comment]
https://github.com/pysal/spvcm/blob/331ed9672531252641b763b83d3a14e8b2216fba/spvcm/sqlite.py#L6

**Comment by ljwolf** [comment]
Yes, that dill import needs to be moved to l151 of that same file where the `dill.loads` is used.

**Comment by jGaboardi** [comment]
My PR from awhile back address this #10

**Comment by jGaboardi** [comment]
Is this ready to merge? It is approved.

**Comment by jGaboardi** [comment]
Also modernizing Travis in #8

**Comment by jGaboardi** [comment]
Closing per #18
