### ISSUE TITLE
new pip and conda-forge packages requested

### ISSUE THREAD

**Issue by sjsrey** [pysal/spvcm#13]
For the pysal-meta release it would be helpful to have  spvcm on conda-forge.  A new version that incorporated changes for #11 and #12 would smooth the meta-release.

**Comment by sjsrey** [comment]
gh [release](https://github.com/pysal/spvcm/releases/tag/untagged-6276576b5d5080348fa0) is ready to  go.

once @ljwolf adds @sjsrey to pypi we can cut the gh release and push to pypi

**Comment by ljwolf** [comment]
Done!

**Comment by jGaboardi** [comment]
Closing per #18
