### ISSUE TITLE
permissions for the steering council

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spvcm#16]
@sjsrey Would be a able to grant admin permission to @martinfleis, @knaaptime, and myself?

**Comment by sjsrey** [comment]
Should now be done:

![image](https://github.com/pysal/spvcm/assets/118042/5283c9d6-88d5-4d22-94e6-80802e9bfdcf)

**Comment by jGaboardi** [comment]
Thanks! Confirmed for myself.
