### ISSUE TITLE
modernize infra - `pyproject.toml` [2024-07-08]

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spvcm#17]
* Migrate to `pyproject.toml`
* https://github.com/pysal/pysal/issues/1277#issuecomment-2215418089

**Comment by martinfleis** [comment]
Wasn't `spvcm` scheduled for archiving?

**Comment by jGaboardi** [comment]
I seem to remember that conversation in a meeting, but can't find where it is documented.

1. Was this documented anywhere?
2. As for the actual archiving...
   1. Should we:
      1. ... add a note to the README that it will be archived on YYYY-MM-DD date?
      2. ... archive immediately (once we have consensus)
3. As for distribution with `pysal/pysal`...
   1. Should we:
      1. ... update the README, docs, landing page, etc. that `spvcm` will not be distributed in the next meta release?
      2. ... everything from (1.) + immediately remove from [`pysal/pysal/pyproject.toml`](https://github.com/pysal/pysal/blob/12ae3c1a59b02e3142d9f9e083c211e8b2fdc314/pyproject.toml#L51)


cc @ljwolf @sjsrey @knaaptime

**Comment by martinfleis** [comment]
> Was this documented anywhere?
https://github.com/orgs/pysal/discussions/1278#discussioncomment-8260977

Don't care how it is going to happen and I don't think anyone will notice.

**Comment by jGaboardi** [comment]
Closing per https://github.com/pysal/spvcm/issues/18
